metadata:
  name: lact
  description: GPU control utility
  arch: x86_64
  license: MIT
  version: 0.8.5
  maintainer: ilya-zlobintsev
  url: https://github.com/ilya-zlobintsev/lact
  source:
    - '../../../../LACT'
  provides: [ lact ]
  conflicts: [ lact-headless ]
  depends:
    all: [ hwdata, vulkan-tools, clinfo ]
    debian-13+ubuntu-2404: [ libgtk-4-1, libdrm2, libdrm-amdgpu1, libadwaita-1-0 ]
    fedora-42+fedora-43: [ gtk4, libdrm, libadwaita ]
    arch: [ gtk4, ocl-icd, libadwaita ]
    opensuse-tumbleweed: [ gtk4, libadwaita-1-0 ]
  build_depends:
    all: [ curl, make, clang, git, vulkan-tools, clinfo ]
    debian-13+ubuntu-2404: [ libgtk-4-dev, pkg-config, build-essential, libdrm-dev, dbus, libadwaita-1-dev ]
    fedora-42+fedora-43: [ gtk4-devel, gcc, libdrm-devel, dbus, libadwaita-devel ]
    arch: [ gtk4, dbus, ocl-icd, libadwaita ]
    opensuse-tumbleweed: [ gtk4-devel, libdrm-devel, libadwaita-devel ]
  all_images: true
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh $RUSTUP_URL
    - cmd: sh /tmp/install_rust.sh -y
    - cmd: bash -c "source $HOME/.cargo/env && rustup toolchain install 1.93.0"
    - cmd: pacman -Syu --noconfirm
      pkg: true
build:
  steps:
    - cmd: bash -c "source $HOME/.cargo/env && cd LACT && make build-release"
install:
  steps:
    - cmd: bash -c "cd $PKGER_BLD_DIR/LACT && DESTDIR=$PKGER_OUT_DIR PREFIX=/usr make install"

