metadata:
  name: lact
  description: AMDGPU control utility
  arch: x86_64
  license: MIT
  version: 0.6.1
  maintainer: ilya-zlobintsev
  url: https://github.com/ilya-zlobintsev/lact
  source:
    - '../../../../LACT'
  provides: [ lact ]
  conflicts: [ lact-headless, lact-libadwaita ]
  depends:
    all: [ hwdata ]
    debian-12+ubuntu-2204+ubuntu-2404: [ libgtk-4-1, libdrm2, libdrm-amdgpu1 ]
    fedora-39+fedora-40+fedora-41: [ gtk4, libdrm ]
    arch: [ gtk4 ]
    opensuse-tumbleweed: [ gtk4 ]
  build_depends:
    all: [ curl, make, clang, git ]
    debian-12+ubuntu-2204+ubuntu-2404: [ libgtk-4-dev, pkg-config, build-essential, libdrm-dev, dbus ]
    fedora-39+fedora-40+fedora-41: [ gtk4-devel, gcc, libdrm-devel, blueprint-compiler, dbus ]
    arch: [ gtk4, blueprint-compiler, dbus ]
    opensuse-tumbleweed: [ gtk4-devel, libdrm-devel, blueprint-compiler ]
  all_images: true
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh $RUSTUP_URL
    - cmd: sh /tmp/install_rust.sh -y --default-toolchain 1.78
    - cmd: >-
        curl -o /tmp/blueprint-compiler.deb http://de.archive.ubuntu.com/ubuntu/pool/universe/b/blueprint-compiler/blueprint-compiler_0.14.0-1_all.deb &&
        apt install -y /tmp/blueprint-compiler.deb
      deb: true
    - cmd: pacman -Syu --noconfirm
      pkg: true
build:
  steps:
    - cmd: bash -c "source $HOME/.cargo/env && cd LACT && make build-release"
install:
  steps:
    - cmd: bash -c "cd $PKGER_BLD_DIR/LACT && DESTDIR=$PKGER_OUT_DIR PREFIX=/usr make install"

