metadata:
  name: lact
  description: AMDGPU control utility
  arch: x86_64
  license: MIT
  version: 0.5.1
  maintainer: ilya-zlobintsev
  url: https://github.com/ilya-zlobintsev/lact
  source:
    - '../../..'
  provides: [ lact ]
  depends:
    all: [ hwdata ]
    debian-12+ubuntu-2204: [ libgtk-4-1 ]
    fedora-38+fedora-39: [ gtk4, libdrm ]
    arch: [ gtk4 ]
  build_depends:
    all: [ curl, make, dbus, clang ]
    debian-12+ubuntu-2204: [ libgtk-4-dev, pkg-config, build-essential, libdrm-dev ]
    fedora-38+fedora-39: [ gtk4-devel, gcc, libdrm-devel, blueprint-compiler ]
    arch: [ gtk4, blueprint-compiler ]
  all_images: true
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh $RUSTUP_URL
    - cmd: sh /tmp/install_rust.sh -y --default-toolchain stable
    - cmd: >-
        curl -o /tmp/blueprint-compiler.deb http://de.archive.ubuntu.com/ubuntu/pool/universe/b/blueprint-compiler/blueprint-compiler_0.10.0-3_all.deb &&
        apt install -y /tmp/blueprint-compiler.deb
      deb: true
build:
  steps:
    - cmd: bash -c "source $HOME/.cargo/env && make"
install:
  steps:
    - cmd: bash -c "cd $PKGER_BLD_DIR && DESTDIR=$PKGER_OUT_DIR PREFIX=/usr make install"

