---
recipes_dir: pkg/recipes
output_dir: pkg/output
images_dir: pkg/images
log_dir: ~
runtime_uri: ~
gpg_key: /tmp/package-signing-key.gpg
gpg_name: Ilya Zlobintsev
ssh: ~
images:
  - name: debian-12
    target: deb
    os: Debian
  - name: fedora-39
    target: rpm
    os: Fedora
  - name: fedora-40
    target: rpm
    os: Fedora
  - name: fedora-41
    target: rpm
    os: Fedora
  - name: ubuntu-2204
    target: deb
    os: Ubuntu
  - name: ubuntu-2404
    target: deb
    os: Ubuntu
  - name: arch
    target: pkg
    os: Arch Linux
  - name: opensuse-tumbleweed
    target: rpm
    os: OpenSUSE
  - name: rhel-8
    target: rpm
    os: Red Hat
  - name: rhel-9
    target: rpm
    os: Red Hat
custom_simple_images: ~
