---
recipes_dir: pkg/recipes
output_dir: pkg/output
images_dir: pkg/images
log_dir: ~
runtime_uri: ~
gpg_key: ~
gpg_name: ~
ssh: ~
images:
  - name: debian-12
    target: deb
  - name: fedora-38
    target: rpm
  - name: fedora-39
    target: rpm
  - name: ubuntu-2204
    target: deb
  - name: arch
    target: pkg
  - name: opensuse-tumbleweed
    target: rpm
custom_simple_images: ~
