[package]
name = "lact-gui"
version = "0.10.1"
authors = ["Ilya Zlobintsev <ilya.zl@protonmail.com>"]
edition.workspace = true

[features]
default = []
gtk-tests = []
bench = ["dep:divan"]

[dependencies]
lact-client = { path = "../lact-client" }
lact-daemon = { path = "../lact-daemon", default-features = false }
lact-schema = { path = "../lact-schema", features = ["args"] }

amdgpu-sysfs = { workspace = true }
nvml-wrapper = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
jiff = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_norway = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
gtk = { version = "0.11.4", package = "gtk4", features = [
    "v4_14",
] }

adw = { package = "libadwaita", version = "0.9.2", features = ["v1_5"] }
relm4 = { version = "0.11.0", features = ["libadwaita"] }
relm4-components = "0.11.0"

i18n-embed = { workspace = true }
i18n-embed-fl = { workspace = true }
rust-embed = { workspace = true }

futures = { workspace = true }
zbus = { workspace = true }

plotters = { version = "0.3.7", default-features = false, features = [
    "area_series",
    "line_series",
    "full_palette",
    "point_series",
] }
plotters-cairo = "0.9.0"
cairo-rs = { version = "0.22", default-features = false }

thread-priority = "3.1.1"

divan = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
