name: Setup Environment
description: Installs dependencies and setups the environment for LACT
runs:
  using: composite
  steps:
    - name: Update repos
      run: sudo apt update
      shell: bash
    - name: Install dependencies
      run: sudo apt install -y libgtk-4-dev pkg-config libvulkan-dev libdrm-dev curl fuse3 libfuse-dev ocl-icd-libopencl1 ocl-icd-opencl-dev
      shell: bash
    - name: Update pci.ids
      run: sudo curl -o /usr/share/hwdata/pci.ids https://pci-ids.ucw.cz/v2.2/pci.ids
      shell: bash
    # A GitHub Action that implements smart caching for rust/cargo projects with sensible defaults.
    - uses: Swatinem/rust-cache@v2