metadata:
  name: lact-headless
  description: AMDGPU control utility
  arch: x86_64
  license: MIT
  version: 0.7.1
  maintainer: ilya-zlobintsev
  url: https://github.com/ilya-zlobintsev/lact
  source:
    - '../../../../LACT'
  provides: [ lact ]
  conflicts: [ lact, lact-libadwaita ]
  depends:
    all: [ hwdata ]
    debian-12+ubuntu-2204+ubuntu-2404: [ libdrm-amdgpu1, libdrm2 ]
    fedora-39+fedora-40+fedora-41+rhel-8+rhel-9: [ libdrm ]
    arch: [ libdrm ]
    opensuse-tumbleweed: [ libdrm ]
  build_depends:
    all: [ curl, make, clang, git ]
    debian-12+ubuntu-2204+ubuntu-2404: [ pkg-config, build-essential, libdrm-dev, dbus ]
    fedora-39+fedora-40+fedora-41+rhel-8+rhel-9: [ gcc, libdrm-devel, dbus ]
    arch: [ libdrm, dbus ]
    opensuse-tumbleweed: [ libdrm-devel ]
  all_images: true
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh $RUSTUP_URL
    - cmd: sh /tmp/install_rust.sh -y --default-toolchain 1.80
    - cmd: pacman -Syu --noconfirm
      pkg: true
build:
  steps:
    - cmd: bash -c "source $HOME/.cargo/env && cd LACT && make build-release-headless"
install:
  steps:
    - cmd: bash -c "cd $PKGER_BLD_DIR/LACT && DESTDIR=$PKGER_OUT_DIR PREFIX=/usr make install"

