metadata:
  name: lact-headless
  description: AMDGPU control utility
  arch: x86_64
  license: MIT
  version: 0.5.1
  maintainer: ilya-zlobintsev
  url: https://github.com/ilya-zlobintsev/lact
  source:
    - '../../..'
  provides: [ lact ]
  depends:
    all: [ hwdata ]
    fedora-38+fedora-39: [ libdrm ]
  build_depends:
    all: [ curl, make, dbus, clang ]
    debian-12+ubuntu-2204: [ pkg-config, build-essential, libdrm-dev ]
    fedora-38+fedora-39: [ gcc, libdrm-devel ]
  all_images: true
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh $RUSTUP_URL
    - cmd: sh /tmp/install_rust.sh -y --default-toolchain stable
build:
  steps:
    - cmd: bash -c "source $HOME/.cargo/env && make build-release"
install:
  steps:
    - cmd: bash -c "cd $PKGER_BLD_DIR && DESTDIR=$PKGER_OUT_DIR PREFIX=/usr make install"

