Name:           lact-headless
Version:        0.5.7
Release:        4
Summary:        AMDGPU control utility
License:        MIT
URL:            https://github.com/ilya-zlobintsev/LACT
Source0:        https://github.com/ilya-zlobintsev/LACT/archive/refs/tags/v0.5.7.tar.gz

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
ExclusiveArch:  x86_64
BuildRequires:  gcc libdrm-devel dbus curl make clang git
Requires:       libdrm hwdata

%description
AMDGPU control utility

%prep
%setup -q

%build
make %{?_smp_mflags}

%install
rm -rf %{buildroot}
make install DESTDIR=%{buildroot}

%files
%defattr(-,root,root,-)
%license LICENSE
%doc README.md
/usr/bin/lact-headless

%changelog
* Sat Nov 09 2024 ilya-zlobintsev - 0.5.7-4. 
- Autogenerated from CI, please see github.com/ilya-zlobintsev/LACT/releases for detailed changelog.
* Sat Nov 09 2024 ilya-zlobintsev - 0.5.7-3. 
- Autogenerated from CI, please see github.com/ilya-zlobintsev/LACT/releases for detailed changelog.
