metadata:
  name: lact-libadwaita
  description: GPU control utility
  arch: x86_64
  license: MIT
  version: 0.8.1
  maintainer: ilya-zlobintsev
  url: https://github.com/ilya-zlobintsev/lact
  source:
    - '../../../../LACT'
  provides: [ lact ]
  conflicts: [ lact, lact-headless ]
  depends:
    all: [ hwdata, vulkan-tools ]
    fedora-41+fedora-42: [ gtk4, libdrm, libadwaita libOpenCL.so.1 ]
    arch: [ gtk4, libadwaita, ocl-icd ]
    opensuse-tumbleweed: [ libdrm, libadwaita, libOpenCL.so.1 ]
  build_depends:
    all: [ curl, make, clang, git, vulkan-tools ]
    fedora-41+fedora-42: [ gtk4-devel, gcc, libdrm-devel, libadwaita-devel, dbus, OpenCL-ICD-Loader-devel ]
    arch: [ gtk4, libadwaita, dbus, ocl-icd ]
    opensuse-tumbleweed: [ libdrm-devel, libadwaita-devel, ocl-icd-devel ]
  all_images: true
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh $RUSTUP_URL
    - cmd: sh /tmp/install_rust.sh -y
    - cmd: bash -c "source $HOME/.cargo/env && rustup toolchain install 1.85.1"
    - cmd: pacman -Syu --noconfirm
      pkg: true
build:
  steps:
    - cmd: bash -c "source $HOME/.cargo/env && cd LACT && make build-release-libadwaita"
install:
  steps:
    - cmd: bash -c "cd $PKGER_BLD_DIR/LACT && DESTDIR=$PKGER_OUT_DIR PREFIX=/usr make install"

