metadata:
  name: lact-libadwaita
  description: AMDGPU control utility (libadwaita GUI)
  arch: x86_64
  license: MIT
  version: 0.5.1
  maintainer: ilya-zlobintsev
  url: https://github.com/ilya-zlobintsev/lact
  source:
    - '../../..'
  provides: [ lact ]
  depends:
    all: [ hwdata ]
    fedora-39: [ gtk4, libdrm, libadwaita ]
    arch: [ gtk4, libadwaita ]
  build_depends:
    all: [ curl, make, dbus, clang ]
    fedora-39: [ gtk4-devel, gcc, libdrm-devel, blueprint-compiler, libadwaita-devel ]
    arch: [ gtk4, blueprint-compiler, libadwaita ]
  all_images: true
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh $RUSTUP_URL
    - cmd: sh /tmp/install_rust.sh -y --default-toolchain stable
build:
  steps:
    - cmd: bash -c "source $HOME/.cargo/env && make build-libadwaita-release"
install:
  steps:
    - cmd: bash -c "cd $PKGER_BLD_DIR && DESTDIR=$PKGER_OUT_DIR PREFIX=/usr make install"

